/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      backgroundImage: {
        'bank-note-1': "url('/covers/bank-note/bank-note-1.svg')",
        'bank-note-2': "url('/covers/bank-note/bank-note-2.svg')",
        'bank-note-3': "url('/covers/bank-note/bank-note-3.svg')",
        'bank-note-4': "url('/covers/bank-note/bank-note-4.svg')",
        'bank-note-5': "url('/covers/bank-note/bank-note-5.svg')",
        'bank-note-6': "url('/covers/bank-note/bank-note-6.svg')",
        'bank-note-7': "url('/covers/bank-note/bank-note-7.svg')",
        'bank-note-8': "url('/covers/bank-note/bank-note-8.svg')",
        'bank-note-9': "url('/covers/bank-note/bank-note-9.svg')",
        'bank-note-10': "url('/covers/bank-note/bank-note-10.svg')",

        'bricks-1': "url('/covers/bricks/bricks-1.svg')",
        'bricks-2': "url('/covers/bricks/bricks-2.svg')",
        'bricks-3': "url('/covers/bricks/bricks-3.svg')",
        'bricks-4': "url('/covers/bricks/bricks-4.svg')",
        'bricks-5': "url('/covers/bricks/bricks-5.svg')",
        'bricks-6': "url('/covers/bricks/bricks-6.svg')",
        'bricks-7': "url('/covers/bricks/bricks-7.svg')",
        'bricks-8': "url('/covers/bricks/bricks-8.svg')",
        'bricks-9': "url('/covers/bricks/bricks-9.svg')",
        'bricks-10': "url('/covers/bricks/bricks-10.svg')",

        'bubbles-1': "url('/covers/bubbles/bubbles-1.svg')",
        'bubbles-2': "url('/covers/bubbles/bubbles-2.svg')",
        'bubbles-3': "url('/covers/bubbles/bubbles-3.svg')",
        'bubbles-4': "url('/covers/bubbles/bubbles-4.svg')",
        'bubbles-5': "url('/covers/bubbles/bubbles-5.svg')",
        'bubbles-6': "url('/covers/bubbles/bubbles-6.svg')",
        'bubbles-7': "url('/covers/bubbles/bubbles-7.svg')",
        'bubbles-8': "url('/covers/bubbles/bubbles-8.svg')",
        'bubbles-9': "url('/covers/bubbles/bubbles-9.svg')",
        'bubbles-10': "url('/covers/bubbles/bubbles-10.svg')",

        'circles-1': "url('/covers/circles/circles-1.svg')",
        'circles-2': "url('/covers/circles/circles-2.svg')",
        'circles-3': "url('/covers/circles/circles-3.svg')",
        'circles-4': "url('/covers/circles/circles-4.svg')",
        'circles-5': "url('/covers/circles/circles-5.svg')",
        'circles-6': "url('/covers/circles/circles-6.svg')",
        'circles-7': "url('/covers/circles/circles-7.svg')",
        'circles-8': "url('/covers/circles/circles-8.svg')",
        'circles-9': "url('/covers/circles/circles-9.svg')",
        'circles-10': "url('/covers/circles/circles-10.svg')",

        'cross-1': "url('/covers/cross/cross-1.svg')",
        'cross-2': "url('/covers/cross/cross-2.svg')",
        'cross-3': "url('/covers/cross/cross-3.svg')",
        'cross-4': "url('/covers/cross/cross-4.svg')",
        'cross-5': "url('/covers/cross/cross-5.svg')",
        'cross-6': "url('/covers/cross/cross-6.svg')",
        'cross-7': "url('/covers/cross/cross-7.svg')",
        'cross-8': "url('/covers/cross/cross-8.svg')",
        'cross-9': "url('/covers/cross/cross-9.svg')",
        'cross-10': "url('/covers/cross/cross-10.svg')",

        'diamonds-1': "url('/covers/diamonds/diamonds-1.svg')",
        'diamonds-2': "url('/covers/diamonds/diamonds-2.svg')",
        'diamonds-3': "url('/covers/diamonds/diamonds-3.svg')",
        'diamonds-4': "url('/covers/diamonds/diamonds-4.svg')",
        'diamonds-5': "url('/covers/diamonds/diamonds-5.svg')",
        'diamonds-6': "url('/covers/diamonds/diamonds-6.svg')",
        'diamonds-7': "url('/covers/diamonds/diamonds-7.svg')",
        'diamonds-8': "url('/covers/diamonds/diamonds-8.svg')",
        'diamonds-9': "url('/covers/diamonds/diamonds-9.svg')",
        'diamonds-10': "url('/covers/diamonds/diamonds-10.svg')",

        'domino-1': "url('/covers/domino/domino-1.svg')",
        'domino-2': "url('/covers/domino/domino-2.svg')",
        'domino-3': "url('/covers/domino/domino-3.svg')",
        'domino-4': "url('/covers/domino/domino-4.svg')",
        'domino-5': "url('/covers/domino/domino-5.svg')",
        'domino-6': "url('/covers/domino/domino-6.svg')",
        'domino-7': "url('/covers/domino/domino-7.svg')",
        'domino-8': "url('/covers/domino/domino-8.svg')",
        'domino-9': "url('/covers/domino/domino-9.svg')",
        'domino-10': "url('/covers/domino/domino-10.svg')",

        'dots-1': "url('/covers/dots/dots-1.svg')",
        'dots-2': "url('/covers/dots/dots-2.svg')",
        'dots-3': "url('/covers/dots/dots-3.svg')",
        'dots-4': "url('/covers/dots/dots-4.svg')",
        'dots-5': "url('/covers/dots/dots-5.svg')",
        'dots-6': "url('/covers/dots/dots-6.svg')",
        'dots-7': "url('/covers/dots/dots-7.svg')",
        'dots-8': "url('/covers/dots/dots-8.svg')",
        'dots-9': "url('/covers/dots/dots-9.svg')",
        'dots-10': "url('/covers/dots/dots-10.svg')",

        'hexagons-1': "url('/covers/hexagons/hexagons-1.svg')",
        'hexagons-2': "url('/covers/hexagons/hexagons-2.svg')",
        'hexagons-3': "url('/covers/hexagons/hexagons-3.svg')",
        'hexagons-4': "url('/covers/hexagons/hexagons-4.svg')",
        'hexagons-5': "url('/covers/hexagons/hexagons-5.svg')",
        'hexagons-6': "url('/covers/hexagons/hexagons-6.svg')",
        'hexagons-7': "url('/covers/hexagons/hexagons-7.svg')",
        'hexagons-8': "url('/covers/hexagons/hexagons-8.svg')",
        'hexagons-9': "url('/covers/hexagons/hexagons-9.svg')",
        'hexagons-10': "url('/covers/hexagons/hexagons-10.svg')",

        'jigsaw-1': "url('/covers/jigsaw/jigsaw-1.svg')",
        'jigsaw-2': "url('/covers/jigsaw/jigsaw-2.svg')",
        'jigsaw-3': "url('/covers/jigsaw/jigsaw-3.svg')",
        'jigsaw-4': "url('/covers/jigsaw/jigsaw-4.svg')",
        'jigsaw-5': "url('/covers/jigsaw/jigsaw-5.svg')",
        'jigsaw-6': "url('/covers/jigsaw/jigsaw-6.svg')",
        'jigsaw-7': "url('/covers/jigsaw/jigsaw-7.svg')",
        'jigsaw-8': "url('/covers/jigsaw/jigsaw-8.svg')",
        'jigsaw-9': "url('/covers/jigsaw/jigsaw-9.svg')",
        'jigsaw-10': "url('/covers/jigsaw/jigsaw-10.svg')",

        'jupiter-1': "url('/covers/jupiter/jupiter-1.svg')",
        'jupiter-2': "url('/covers/jupiter/jupiter-2.svg')",
        'jupiter-3': "url('/covers/jupiter/jupiter-3.svg')",
        'jupiter-4': "url('/covers/jupiter/jupiter-4.svg')",
        'jupiter-5': "url('/covers/jupiter/jupiter-5.svg')",
        'jupiter-6': "url('/covers/jupiter/jupiter-6.svg')",
        'jupiter-7': "url('/covers/jupiter/jupiter-7.svg')",
        'jupiter-8': "url('/covers/jupiter/jupiter-8.svg')",
        'jupiter-9': "url('/covers/jupiter/jupiter-9.svg')",
        'jupiter-10': "url('/covers/jupiter/jupiter-10.svg')",

        'leafs-1': "url('/covers/leafs/leafs-1.svg')",
        'leafs-2': "url('/covers/leafs/leafs-2.svg')",
        'leafs-3': "url('/covers/leafs/leafs-3.svg')",
        'leafs-4': "url('/covers/leafs/leafs-4.svg')",
        'leafs-5': "url('/covers/leafs/leafs-5.svg')",
        'leafs-6': "url('/covers/leafs/leafs-6.svg')",
        'leafs-7': "url('/covers/leafs/leafs-7.svg')",
        'leafs-8': "url('/covers/leafs/leafs-8.svg')",
        'leafs-9': "url('/covers/leafs/leafs-9.svg')",
        'leafs-10': "url('/covers/leafs/leafs-10.svg')",

        'melt-1': "url('/covers/melt/melt-1.svg')",
        'melt-2': "url('/covers/melt/melt-2.svg')",
        'melt-3': "url('/covers/melt/melt-3.svg')",
        'melt-4': "url('/covers/melt/melt-4.svg')",
        'melt-5': "url('/covers/melt/melt-5.svg')",
        'melt-6': "url('/covers/melt/melt-6.svg')",
        'melt-7': "url('/covers/melt/melt-7.svg')",
        'melt-8': "url('/covers/melt/melt-8.svg')",
        'melt-9': "url('/covers/melt/melt-9.svg')",
        'melt-10': "url('/covers/melt/melt-10.svg')",

        'squares-1': "url('/covers/squares/squares-1.svg')",
        'squares-2': "url('/covers/squares/squares-2.svg')",
        'squares-3': "url('/covers/squares/squares-3.svg')",
        'squares-4': "url('/covers/squares/squares-4.svg')",
        'squares-5': "url('/covers/squares/squares-5.svg')",
        'squares-6': "url('/covers/squares/squares-6.svg')",
        'squares-7': "url('/covers/squares/squares-7.svg')",
        'squares-8': "url('/covers/squares/squares-8.svg')",
        'squares-9': "url('/covers/squares/squares-9.svg')",
        'squares-10': "url('/covers/squares/squares-10.svg')",

        'stripes-1': "url('/covers/stripes/stripes-1.svg')",
        'stripes-2': "url('/covers/stripes/stripes-2.svg')",
        'stripes-3': "url('/covers/stripes/stripes-3.svg')",
        'stripes-4': "url('/covers/stripes/stripes-4.svg')",
        'stripes-5': "url('/covers/stripes/stripes-5.svg')",
        'stripes-6': "url('/covers/stripes/stripes-6.svg')",
        'stripes-7': "url('/covers/stripes/stripes-7.svg')",
        'stripes-8': "url('/covers/stripes/stripes-8.svg')",
        'stripes-9': "url('/covers/stripes/stripes-9.svg')",
        'stripes-10': "url('/covers/stripes/stripes-10.svg')",

        'tic-tac-toe-1': "url('/covers/tic-tac-toe/tic-tac-toe-1.svg')",
        'tic-tac-toe-2': "url('/covers/tic-tac-toe/tic-tac-toe-2.svg')",
        'tic-tac-toe-3': "url('/covers/tic-tac-toe/tic-tac-toe-3.svg')",
        'tic-tac-toe-4': "url('/covers/tic-tac-toe/tic-tac-toe-4.svg')",
        'tic-tac-toe-5': "url('/covers/tic-tac-toe/tic-tac-toe-5.svg')",
        'tic-tac-toe-6': "url('/covers/tic-tac-toe/tic-tac-toe-6.svg')",
        'tic-tac-toe-7': "url('/covers/tic-tac-toe/tic-tac-toe-7.svg')",
        'tic-tac-toe-8': "url('/covers/tic-tac-toe/tic-tac-toe-8.svg')",
        'tic-tac-toe-9': "url('/covers/tic-tac-toe/tic-tac-toe-9.svg')",
        'tic-tac-toe-10': "url('/covers/tic-tac-toe/tic-tac-toe-10.svg')",

        'triangles-1': "url('/covers/triangles/triangles-1.svg')",
        'triangles-2': "url('/covers/triangles/triangles-2.svg')",
        'triangles-3': "url('/covers/triangles/triangles-3.svg')",
        'triangles-4': "url('/covers/triangles/triangles-4.svg')",
        'triangles-5': "url('/covers/triangles/triangles-5.svg')",
        'triangles-6': "url('/covers/triangles/triangles-6.svg')",
        'triangles-7': "url('/covers/triangles/triangles-7.svg')",
        'triangles-8': "url('/covers/triangles/triangles-8.svg')",
        'triangles-9': "url('/covers/triangles/triangles-9.svg')",
        'triangles-10': "url('/covers/triangles/triangles-10.svg')",

        'yyy-1': "url('/covers/yyy/yyy-1.svg')",
        'yyy-2': "url('/covers/yyy/yyy-2.svg')",
        'yyy-3': "url('/covers/yyy/yyy-3.svg')",
        'yyy-4': "url('/covers/yyy/yyy-4.svg')",
        'yyy-5': "url('/covers/yyy/yyy-5.svg')",
        'yyy-6': "url('/covers/yyy/yyy-6.svg')",
        'yyy-7': "url('/covers/yyy/yyy-7.svg')",
        'yyy-8': "url('/covers/yyy/yyy-8.svg')",
        'yyy-9': "url('/covers/yyy/yyy-9.svg')",
        'yyy-10': "url('/covers/yyy/yyy-10.svg')",
      },
    },
  },
  plugins: [],
};
