const coversFlower = [
  '/covers/flower/flower-1.svg',
  '/covers/flower/flower-2.svg',
  '/covers/flower/flower-3.svg',
  '/covers/flower/flower-4.svg',
  '/covers/flower/flower-5.svg',
  '/covers/flower/flower-6.svg',
  '/covers/flower/flower-7.svg',
  '/covers/flower/flower-8.svg',
  '/covers/flower/flower-9.svg',
  '/covers/flower/flower-10.svg',
  '/covers/flower/flower-11.svg',
  '/covers/flower/flower-12.svg',
  '/covers/flower/flower-13.svg',
  '/covers/flower/flower-14.svg',
  '/covers/flower/flower-15.svg',
  '/covers/flower/flower-16.svg',
  '/covers/flower/flower-17.svg',
  '/covers/flower/flower-18.svg',
  '/covers/flower/flower-19.svg',
  '/covers/flower/flower-20.svg',
  '/covers/flower/flower-21.svg',
  '/covers/flower/flower-22.svg',
  '/covers/flower/flower-23.svg',
  '/covers/flower/flower-24.svg',
];

export default coversFlower;
